// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvbfvcsucpiyqqcyyiqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2YmZ2Y3N1Y3BpeXFxY3l5aXFuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NTQ2NDQsImV4cCI6MjA2ODQzMDY0NH0._k_ewaPems77K8zKoHsscS56gEI8ZoyzSnBqdEuM7TM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});